[package]
name = "quicksauce"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.8.0"
clap = "4.5.8"
uuid = "1.9.1"
